[general]
live_config_reload = true

[terminal]
shell = "nu"

[font]
size = 10

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Atkinson Hyperlegible Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = false
opacity = 0.92

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 0
y = 0

[cursor]
style = "Block"
unfocused_hollow = true

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = '#1e1c31'
foreground = '#cbe1e7'

[colors.cursor]
text = '#ff271d'
cursor = '#fbfcfc'

# Normal colors
[colors.normal]
black   = '#141228'
red     = '#ff5458'
green   = '#62d196'
yellow  = '#ffb378'
blue    = '#65b2ff'
magenta = '#906cff'
cyan    = '#63f2f1'
white   = '#a6b3cc'

# Bright colors
[colors.bright]
black   = '#565575'
red     = '#ff8080'
green   = '#95ffa4'
yellow  = '#ffe9aa'
blue    = '#91ddff'
magenta = '#c991e1'
cyan    = '#aaffe4'
white   = '#cbe3e7'
