[general]
import = ["themes/current.toml"]

live_config_reload = true

[terminal]
shell = "nu"

[font]
size = 10

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Atkinson Hyperlegible Mono"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = false

[window.dimensions]
columns = 100
lines = 40

[window.padding]
x = 0
y = 0

[cursor]
style = "Block"
unfocused_hollow = true

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = false
